apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: Template for building Dyncamic Admission WebHook
    tags: infrastructure
  name: ${NAME}
objects:
- kind: "BuildConfig"
  apiVersion: "build.openshift.io/v1"
  metadata:
    name: ${NAME}
    namespace: ${NAMESPACE}
  spec:
    runPolicy: "Serial"
    source:
      git:
        uri: ${GIT_URL}
    strategy:
      sourceStrategy:
        from:
          kind: "DockerImage"
          name: "docker.io/dimssss/golang-s2i:0.5"
    output:
      to:
        kind: "DockerImage"
        name: "docker.io/dimssss/${NAME}:${VERSION}"
      pushSecret:
        name: docker-hub-dimssss
parameters:
- description: Name
  name: NAME
  value: "rdbc-operator"
  required: true
- description: Specify current namespace
  name: NAMESPACE
  value: "darp"
  required: true
- description: Specify service GIT url
  name: GIT_URL
  value: "https://github.com/dimss/rdbc-operator"
  required: true
- description: Specify version
  name: VERSION
  value: "0.2"
  required: true
