apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rdbcs.rdbc.cnative
spec:
  group: rdbc.cnative
  names:
    kind: Rdbc
    listKind: RdbcList
    plural: rdbcs
    singular: rdbc
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            name:
              type: string
            namespace:
              type: string
            size:
              type: string
          required:
          - namespace
          - name
          - size
          type: object
        status:
          properties:
            dbEndpointIp:
              type: string
            dbEndpointUrl:
              type: string
          required:
          - dbEndpointUrl
          - dbEndpointIp
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
