apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: rdbc-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - rdbc-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
- apiGroups:
  - rdbc.cnative
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rdbc-operator
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rdbc-operator
subjects:
- kind: ServiceAccount
  name: rdbc-operator
  namespace: op
roleRef:
  kind: ClusterRole
  name: rdbc-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rdbc-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rdbc-operator
  template:
    metadata:
      labels:
        name: rdbc-operator
    spec:
      serviceAccountName: rdbc-operator
      containers:
        - name: rdbc-operator
          image: dimssss/rdbc:0.1
          command:
          - rdbc-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "rdbc-operator"
            - name: REDIS_CRED_SECRET
              value: "redis-enterprise"
            - name: REDIS_SERVICE_NAME
              value: "redis-enterprise"
            - name: REDIS_NS
              value: "redis"
            - name: REDIS_API
              value: "https://redis-enterprise-redis.router.default.svc.cluster.local"