apiVersion: apps/v1
kind: Deployment
metadata:
  name: rdbc-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rdbc-operator
  template:
    metadata:
      labels:
        name: rdbc-operator
    spec:
      serviceAccountName: rdbc-operator
      containers:
        - name: rdbc-operator
          image: dimssss/rdbc:0.1
          command:
          - rdbc-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "rdbc-operator"
            - name: REDIS_CRED_SECRET
              value: "redis-enterprise"
            - name: REDIS_SERVICE_NAME
              value: "redis-enterprise"
            - name: REDIS_NS
              value: "redis"
            - name: REDIS_API
              value: "https://redis-enterprise-redis.router.default.svc.cluster.local"

