kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rdbc-operator
subjects:
- kind: ServiceAccount
  name: rdbc-operator
  namespace: op
roleRef:
  kind: ClusterRole
  name: rdbc-operator
  apiGroup: rbac.authorization.k8s.io
