// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/rdbc-operator/pkg/apis/rdbc/v1alpha1.Rdbc":       schema_pkg_apis_rdbc_v1alpha1_Rdbc(ref),
		"github.com/rdbc-operator/pkg/apis/rdbc/v1alpha1.RdbcSpec":   schema_pkg_apis_rdbc_v1alpha1_RdbcSpec(ref),
		"github.com/rdbc-operator/pkg/apis/rdbc/v1alpha1.RdbcStatus": schema_pkg_apis_rdbc_v1alpha1_RdbcStatus(ref),
	}
}

func schema_pkg_apis_rdbc_v1alpha1_Rdbc(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Rdbc is the Schema for the rdbcs API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/rdbc-operator/pkg/apis/rdbc/v1alpha1.RdbcSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/rdbc-operator/pkg/apis/rdbc/v1alpha1.RdbcStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/rdbc-operator/pkg/apis/rdbc/v1alpha1.RdbcSpec", "github.com/rdbc-operator/pkg/apis/rdbc/v1alpha1.RdbcStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_rdbc_v1alpha1_RdbcSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "RdbcSpec defines the desired state of Rdbc",
				Properties: map[string]spec.Schema{
					"namespace": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"name": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"size": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
				},
				Required: []string{"namespace", "name", "size"},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_rdbc_v1alpha1_RdbcStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "RdbcStatus defines the observed state of Rdbc",
				Properties: map[string]spec.Schema{
					"dbEndpointUrl": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"dbEndpointIp": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
				},
				Required: []string{"dbEndpointUrl", "dbEndpointIp"},
			},
		},
		Dependencies: []string{},
	}
}
